
package guesthouse;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import myFrame.frmAddService;
import myFrame.frmBooking;
import myFrame.frmCheckIn;
import myFrame.frmCheckOut;
import myFrame.frmSetRoomPrice;
import myFrame.frmSetupUser;
import myFrame.frmViewRoom;

public class MainForm extends javax.swing.JFrame {

   
    public MainForm() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);

      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCheckIn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAddService = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        TBooking = new javax.swing.JMenu();
        TCheckIn = new javax.swing.JMenuItem();
        TBookiing = new javax.swing.JMenuItem();
        TCheckOut = new javax.swing.JMenuItem();
        jSearch = new javax.swing.JMenu();
        jUtility = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        USetRoomPrice = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSecurity = new javax.swing.JMenu();
        jStock = new javax.swing.JMenu();
        jReport = new javax.swing.JMenu();
        jAbout = new javax.swing.JMenu();
        jHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        jCheckIn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vichea\\Documents\\NetBeansProjects\\GuestHouse\\icons\\checkin_32.png")); // NOI18N
        jCheckIn.setText("Check in");
        jCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckInMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vichea\\Documents\\NetBeansProjects\\GuestHouse\\icons\\Booking_32.png")); // NOI18N
        jLabel3.setText("Booking");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vichea\\Documents\\NetBeansProjects\\GuestHouse\\icons\\ViewRoom_32.png")); // NOI18N
        jLabel4.setText("View Room");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vichea\\Documents\\NetBeansProjects\\GuestHouse\\icons\\CheckOut_32.png")); // NOI18N
        jLabel5.setText("Check Out");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vichea\\Documents\\NetBeansProjects\\GuestHouse\\icons\\SetupUser_32.png")); // NOI18N
        jLabel7.setText("Setup User");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        btnAddService.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAddService.setForeground(new java.awt.Color(255, 255, 255));
        btnAddService.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vichea\\Documents\\NetBeansProjects\\GuestHouse\\icons\\AddService_32.png")); // NOI18N
        btnAddService.setText("Add Service");
        btnAddService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddServiceMouseClicked(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vichea\\Documents\\NetBeansProjects\\GuestHouse\\icons\\Exit_32.png")); // NOI18N
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vichea\\Documents\\NetBeansProjects\\GuestHouse\\icons\\logout_32.png")); // NOI18N
        jLabel10.setText("LogOut");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jCheckIn)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnAddService)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckIn)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(btnAddService)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(970, 457));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        jMenuBar1.setMargin(new java.awt.Insets(0, 10, 0, 0));

        jFile.setText("File");
        jFile.setMargin(new java.awt.Insets(0, 0, 0, 20));

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Save");
        jMenuItem9.setMargin(new java.awt.Insets(5, 0, 5, 0));
        jFile.add(jMenuItem9);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Print");
        jMenuItem7.setMargin(new java.awt.Insets(5, 0, 5, 0));
        jFile.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Exit");
        jMenuItem8.setMargin(new java.awt.Insets(5, 0, 5, 0));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jFile.add(jMenuItem8);

        jMenuBar1.add(jFile);

        TBooking.setText("Transition");
        TBooking.setMargin(new java.awt.Insets(0, 0, 0, 20));

        TCheckIn.setText("Check In");
        TCheckIn.setMargin(new java.awt.Insets(5, 0, 5, 0));
        TCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCheckInActionPerformed(evt);
            }
        });
        TBooking.add(TCheckIn);

        TBookiing.setText("Booking");
        TBookiing.setMargin(new java.awt.Insets(5, 0, 5, 0));
        TBookiing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBookiingActionPerformed(evt);
            }
        });
        TBooking.add(TBookiing);

        TCheckOut.setText("Check Out");
        TCheckOut.setMargin(new java.awt.Insets(5, 0, 5, 0));
        TCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCheckOutActionPerformed(evt);
            }
        });
        TBooking.add(TCheckOut);

        jMenuBar1.add(TBooking);

        jSearch.setText("Search");
        jSearch.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jSearch);

        jUtility.setText("Utility");
        jUtility.setMargin(new java.awt.Insets(0, 0, 0, 20));

        jMenuItem2.setText("Customer Information");
        jUtility.add(jMenuItem2);

        USetRoomPrice.setText("Set Room Price");
        USetRoomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USetRoomPriceActionPerformed(evt);
            }
        });
        jUtility.add(USetRoomPrice);

        jMenuItem4.setText("Room information");
        jUtility.add(jMenuItem4);

        jMenuBar1.add(jUtility);

        jSecurity.setText("Security");
        jSecurity.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jSecurity);

        jStock.setText("Stock");
        jStock.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jStock);

        jReport.setText("Report");
        jReport.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jReport);

        jAbout.setText("About");
        jAbout.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jAbout);

        jHelp.setText("Help");
        jHelp.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TBookiingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBookiingActionPerformed
        frmBooking bkg = new frmBooking();
        bkg.show();
    }//GEN-LAST:event_TBookiingActionPerformed

    private void TCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCheckInActionPerformed
        frmCheckIn cki = new frmCheckIn();
        cki.show();
    }//GEN-LAST:event_TCheckInActionPerformed

    private void TCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCheckOutActionPerformed
        frmCheckOut cko = new frmCheckOut();
        cko.show();
    }//GEN-LAST:event_TCheckOutActionPerformed

    private void USetRoomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USetRoomPriceActionPerformed
        frmSetRoomPrice srp = new frmSetRoomPrice();
        srp.show();
    }//GEN-LAST:event_USetRoomPriceActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        Component Frame = new JFrame("Exit");

        if (JOptionPane.showConfirmDialog( Frame,"confirm if you Want to Exit","Name of the Application or Title",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
         System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnAddServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddServiceMouseClicked
        frmAddService addS = new frmAddService();
        addS.show();
    }//GEN-LAST:event_btnAddServiceMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        frmSetupUser set = new frmSetupUser();
        set.show();

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        frmCheckOut ckOut = new  frmCheckOut();
        ckOut.show();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        frmViewRoom vRoom = new frmViewRoom();
        vRoom.show();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        frmBooking book = new frmBooking();
        book.show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jCheckInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckInMouseClicked
        // TODO add your handling code here:
        frmCheckIn checkIn = new frmCheckIn();

        checkIn.show();
    }//GEN-LAST:event_jCheckInMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Component Frame = new JFrame("Exit");

        if (JOptionPane.showConfirmDialog( Frame,"confirm if you Want to Exit","Name of the Application or Title",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
         System.exit(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
//            frmLogin form = new frmLogin();
//            form.show();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem TBookiing;
    private javax.swing.JMenu TBooking;
    private javax.swing.JMenuItem TCheckIn;
    private javax.swing.JMenuItem TCheckOut;
    private javax.swing.JMenuItem USetRoomPrice;
    private javax.swing.JLabel btnAddService;
    private javax.swing.JLabel btnExit;
    private javax.swing.JMenu jAbout;
    private javax.swing.JLabel jCheckIn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jFile;
    private javax.swing.JMenu jHelp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jReport;
    private javax.swing.JMenu jSearch;
    private javax.swing.JMenu jSecurity;
    private javax.swing.JMenu jStock;
    private javax.swing.JMenu jUtility;
    // End of variables declaration//GEN-END:variables
}
