
package geust_house.guesthouse;

import geust_house.myFrame.SqlConfigString;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import geust_house.myFrame.frmAddService;
import geust_house.myFrame.frmBooking;
import geust_house.myFrame.frmCheckIn;
import geust_house.myFrame.frmCheckOut;
import geust_house.myFrame.frmDirectCheckIn;
import geust_house.myFrame.frmSetRoomPrice;
import geust_house.myFrame.frmSetupUser;
import geust_house.myFrame.frmViewRoom;
import geust_house.myFrame.frmChangeRoom;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

public class MainForm extends javax.swing.JFrame {

    DataConnection data=new DataConnection();
    Statement stm;
    DefaultComboBoxModel cmb=new DefaultComboBoxModel<>();
    ResultSet res;
    Calendar cal=Calendar.getInstance();
    PreparedStatement pst=null;
    int room_id,book_id;
    Date check_out_date=null,current_date;
     SimpleDateFormat frm=new SimpleDateFormat("YYYY-MM-dd HH-mm-ss");
    public MainForm() {
         initComponents();
         setExtendedState(JFrame.MAXIMIZED_BOTH);
     
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jCheckIn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnAddService = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnChangeRoom = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jFile = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        TBooking = new javax.swing.JMenu();
        mCheckInDtail = new javax.swing.JMenu();
        mCheckIn = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        mCheckOutDetail = new javax.swing.JMenu();
        mCheckOut = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        mBooking = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mStaff = new javax.swing.JMenuItem();
        mProduct = new javax.swing.JMenuItem();
        mUtilites = new javax.swing.JMenuItem();
        mRepair = new javax.swing.JMenuItem();
        mOther = new javax.swing.JMenuItem();
        jSearch = new javax.swing.JMenu();
        jUtility = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        USetRoomPrice = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSecurity = new javax.swing.JMenu();
        jStock = new javax.swing.JMenu();
        jReport = new javax.swing.JMenu();
        jAbout = new javax.swing.JMenu();
        jHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        jCheckIn.setText("Check in");
        jCheckIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckInMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Booking");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("View Room");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Check Out");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Setup User");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        btnAddService.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnAddService.setForeground(new java.awt.Color(255, 255, 255));
        btnAddService.setText("Add Service");
        btnAddService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddServiceMouseClicked(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LogOut");

        btnChangeRoom.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnChangeRoom.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeRoom.setText("Change Room");
        btnChangeRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangeRoomMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jCheckIn)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnAddService)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChangeRoom)
                .addGap(36, 36, 36)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckIn)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(btnAddService)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(btnExit)
                    .addComponent(btnChangeRoom))
                .addContainerGap())
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(970, 457));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 894, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        jMenuBar1.setMargin(new java.awt.Insets(0, 10, 0, 0));

        jFile.setText("File");
        jFile.setMargin(new java.awt.Insets(0, 0, 0, 20));

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Save");
        jMenuItem9.setMargin(new java.awt.Insets(5, 0, 5, 0));
        jFile.add(jMenuItem9);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Print");
        jMenuItem7.setMargin(new java.awt.Insets(5, 0, 5, 0));
        jFile.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Exit");
        jMenuItem8.setMargin(new java.awt.Insets(5, 0, 5, 0));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jFile.add(jMenuItem8);

        jMenuBar1.add(jFile);

        TBooking.setText("Transition");
        TBooking.setMargin(new java.awt.Insets(0, 0, 0, 20));

        mCheckInDtail.setText("Chexk In");

        mCheckIn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        mCheckIn.setText("Check In");
        mCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCheckInActionPerformed(evt);
            }
        });
        mCheckInDtail.add(mCheckIn);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Check in Detail");
        mCheckInDtail.add(jMenuItem3);

        TBooking.add(mCheckInDtail);

        mCheckOutDetail.setText("Check out");

        mCheckOut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mCheckOut.setText("Check Out");
        mCheckOutDetail.add(mCheckOut);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Check Out Detail");
        mCheckOutDetail.add(jMenuItem1);

        TBooking.add(mCheckOutDetail);

        jMenu1.setText("Booking");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Booking");
        jMenu1.add(jMenuItem5);

        mBooking.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mBooking.setText("Booking Detail");
        jMenu1.add(mBooking);

        TBooking.add(jMenu1);

        jMenu2.setText("Expense");

        mStaff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mStaff.setText("Staff");
        mStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mStaffActionPerformed(evt);
            }
        });
        jMenu2.add(mStaff);

        mProduct.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mProduct.setText("Product");
        jMenu2.add(mProduct);

        mUtilites.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        mUtilites.setText("Utilites");
        jMenu2.add(mUtilites);

        mRepair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        mRepair.setText("Repair");
        jMenu2.add(mRepair);

        mOther.setText("Other");
        jMenu2.add(mOther);

        TBooking.add(jMenu2);

        jMenuBar1.add(TBooking);

        jSearch.setText("Search");
        jSearch.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jSearch);

        jUtility.setText("Utility");
        jUtility.setMargin(new java.awt.Insets(0, 0, 0, 20));

        jMenuItem2.setText("Customer Information");
        jUtility.add(jMenuItem2);

        USetRoomPrice.setText("Set Room Price");
        USetRoomPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USetRoomPriceActionPerformed(evt);
            }
        });
        jUtility.add(USetRoomPrice);

        jMenuItem4.setText("Room information");
        jUtility.add(jMenuItem4);

        jMenuBar1.add(jUtility);

        jSecurity.setText("Security");
        jSecurity.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jSecurity);

        jStock.setText("Stock");
        jStock.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jStock);

        jReport.setText("Report");
        jReport.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jReport);

        jAbout.setText("About");
        jAbout.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jAbout);

        jHelp.setText("Help");
        jHelp.setMargin(new java.awt.Insets(0, 0, 0, 20));
        jMenuBar1.add(jHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 894, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void USetRoomPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USetRoomPriceActionPerformed
        frmSetRoomPrice srp = new frmSetRoomPrice();
        srp.show();
    }//GEN-LAST:event_USetRoomPriceActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        Component Frame = new JFrame("Exit");

        if (JOptionPane.showConfirmDialog( Frame,"confirm if you Want to Exit","Name of the Application or Title",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
         System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnAddServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddServiceMouseClicked
        geust_house.myFrame.frmAddService addS = new  geust_house.myFrame.frmAddService();
        addS.show();
    }//GEN-LAST:event_btnAddServiceMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        frmSetupUser set = new frmSetupUser();
        set.show();

    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        frmCheckOut ckOut = new  frmCheckOut();
        ckOut.show();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        frmViewRoom vRoom = new frmViewRoom();
        vRoom.show();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       frmBooking f=new frmBooking();
       f.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jCheckInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckInMouseClicked
       Object[] option={"Yes","No"};
       int res=JOptionPane.showOptionDialog(new JFrame(),"Already Booked or Not?","Check In",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null, option,option[0]);
       if(res==JOptionPane.YES_OPTION){
         new frmCheckIn().setVisible(true);
       }
       else{
          new frmDirectCheckIn().setVisible(true);
       }
    }//GEN-LAST:event_jCheckInMouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Component Frame = new JFrame("Exit");

        if (JOptionPane.showConfirmDialog( Frame,"confirm if you Want to Exit","Name of the Application or Title",
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
         System.exit(0);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          try {
              int cancel_book_id=0;
            
              try {
                  pst=data.getConnectio().prepareStatement(SQLString.MAX_ID_CANCELBOOK);
              } catch (ClassNotFoundException ex) {
                  Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                  Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IllegalAccessException ex) {
                  Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
              }
                    res=pst.executeQuery();
                    while(res.next()){
                    cancel_book_id=res.getInt(1);
                    }
                    res.close();                    
              try {
                  pst=data.getConnectio().prepareStatement("select * from view_book_checkout_date;");
              } catch (ClassNotFoundException ex) {
                  Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
              } catch (InstantiationException ex) {
                  Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
              } catch (IllegalAccessException ex) {
                  Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
              }
                 res=pst.executeQuery();
                 String currentDate=frm.format(cal.getTime());
            
            while(res.next()){
                room_id=res.getInt(1);
                book_id=res.getInt(2);
                int cus_id=res.getInt(5);
                if(currentDate.compareTo(res.getDate(3).toString())>0){
                    JOptionPane.showMessageDialog(this,"Room No. "+res.getInt(1)+" has been Cancel Booking ");
                    int duration=(int) ((res.getDate(3).getTime()-res.getDate(4).getTime())/(1000*3600*24));
                    try {
                        //update Book_status in book detail
                        pst=data.getConnectio().prepareStatement(SQLString.CANCELBOOKING);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    pst.setInt(1,room_id);
                    pst.execute();
                    pst.close();
                    try {
                        //insert into cancel book
                        pst=data.getConnectio().prepareStatement(SQLString.INSERT_INTO_CANCELBOOK);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    pst.setString(1,currentDate);
                    pst.setInt(2, 1);
                    pst.setInt(3, book_id);
                    pst.setInt(4,cus_id);
                    pst.execute();
                    pst.close();
                    JOptionPane.showMessageDialog(this,currentDate+ book_id+cus_id);               
                    
                    try {
                        //insert into cancel_book_detail
                        pst=data.getConnectio().prepareStatement(SQLString.INSERT_INTO_CANCELBOOK_DETAIL);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    pst.setInt(1,(cancel_book_id)+1);
                    pst.setInt(2,room_id);
                    pst.setInt(3,duration);
                    pst.setDouble(4,0.00);
                    pst.execute();
                    pst.close();
                    try {
                        //update room status
                        pst=data.getConnectio().prepareStatement(SQLString.UPDATE_ROOM_STATUS);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    pst.setInt(1,1);
                    pst.setInt(2,room_id);
                    pst.execute();
                    pst.close();
                }
                else{
                    JOptionPane.showMessageDialog(this,"nth");
                }
            }
            res.close();
            } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void mCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCheckInActionPerformed
       Object[] options={"Yes","No","Cancel"};
       int res=JOptionPane.showOptionDialog(new JFrame(),"Guest has been booked already or not? ","Check In",1, 1, null, options, options[0]);
        switch (res) {
            case JOptionPane.OK_OPTION:
                new frmCheckIn().setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                new frmDirectCheckIn().setVisible(true);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_mCheckInActionPerformed

    private void mStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mStaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mStaffActionPerformed

    private void btnChangeRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangeRoomMouseClicked
        new frmChangeRoom().setVisible(true);
    }//GEN-LAST:event_btnChangeRoomMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
//            frmLogin form = new frmLogin();
//            form.show();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu TBooking;
    private javax.swing.JMenuItem USetRoomPrice;
    private javax.swing.JLabel btnAddService;
    private javax.swing.JLabel btnChangeRoom;
    private javax.swing.JLabel btnExit;
    private javax.swing.JMenu jAbout;
    private javax.swing.JLabel jCheckIn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jFile;
    private javax.swing.JMenu jHelp;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jReport;
    private javax.swing.JMenu jSearch;
    private javax.swing.JMenu jSecurity;
    private javax.swing.JMenu jStock;
    private javax.swing.JMenu jUtility;
    private javax.swing.JMenuItem mBooking;
    private javax.swing.JMenuItem mCheckIn;
    private javax.swing.JMenu mCheckInDtail;
    private javax.swing.JMenuItem mCheckOut;
    private javax.swing.JMenu mCheckOutDetail;
    private javax.swing.JMenuItem mOther;
    private javax.swing.JMenuItem mProduct;
    private javax.swing.JMenuItem mRepair;
    private javax.swing.JMenuItem mStaff;
    private javax.swing.JMenuItem mUtilites;
    // End of variables declaration//GEN-END:variables
}
